# This playbook is executed at the end of the install process
---
- hosts: all
  tasks:
    # fix locale settings after installation (opensuse quirk)
    # copy language from /etc/locale.conf to /etc/sysconfig/language
    - name: set the language in /etc/sysconfig/language
      lineinfile:
        path: /etc/sysconfig/language
        regexp: '^RC_LANG'
        line: 'RC_LANG="{{ item }}"'
      with_items: "{{ lookup('ini', 'LANG type=properties file=/etc/locale.conf') }}"

    - name: enable translation periodic check
      systemd: name=zigzag-languages.timer enabled=yes

    - name: remove live medium tools
      zypper: name={{item}} state=absent
      with_items:
        - calamares
        - zigzag-live-service
        - dracut-kiwi-live
