---
- name: install samba packages
  zypper:
    name:
      - samba
      - samba-client
      - cifs-utils
    state: present

- name: setup usershares directory
  file:
    path: /var/lib/samba/usershares
    owner: root
    group: users
    state: directory
    mode: 01770

- name: copy samba configuration
  copy:
    src: smb.conf
    dest: /etc/samba/smb.conf

- name: enable smb service
  systemd: name=smb enabled=yes

- name: enable nmb service
  systemd: name=nmb enabled=yes
